### PR TITLE
import TPrint from https://github.com/lihaoyi/upickle-pprint

### PR DESCRIPTION
**Pull request by MasseGuillaume**
I'm adding the documentation: http://www.lihaoyi.com/upickle-pprint/pprint/#TPrint in the next commit.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
I think everything is imported now. Let me know if I missed anything.

**Comment by lihaoyi** [comment]
@MasseGuillaume I won't have time to properly review, so I say you go for it as long as it works for you. When the time comes to make Ammonite start using this repo, I'll raise any issues I find then. 

Again, just ping me if you want me to publishSigned it, or I can give you my publishing keys if you want to be able to iterate independently without blocking on me

**Comment by MasseGuillaume** [comment]
Understood. Is it possible to add my pgp key to Sonatype?

**Comment by lihaoyi** [comment]
i have gittered you my publishing token

**Comment by MasseGuillaume** [comment]
Awesome. When I find the time, I will cut a release to get started with this new repo. I also need to put the scalatex output on github pages.

**Pull request merged**
